---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-multi-stage
spec:
  params:
    - name: person
      description: Name of person to greet
      default: John
      type: string
  steps:
    - name: write-hello
      image: alpine
      script: |
        #!/usr/bin/env sh
        echo Preparing greeting
        echo Hello $(params.person) > ~/hello.txt
        sleep 2
        echo Done!
    - name: say-hello
      image: node:14
      script: |
        #!/usr/bin/env node
        let fs = require("fs");
        let file = "/tekton/home/hello.txt";
        let fileContent = fs.readFileSync(file).toString();
        console.log(fileContent);