---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-with-params
spec:
  params:
    - name: person
      description: Name of person to greet
      default: John
      type: string
  steps:
    - name: say-hello
      image: alpine
      command:
        - /bin/sh
      args: ['-c', 'echo Hello $(params.person)']